# Generated by Django 4.1.5 on 2023-02-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('correctAnswers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video1', models.IntegerField(default=0)),
                ('video2', models.IntegerField(default=0)),
                ('video3', models.IntegerField(default=0)),
                ('video4', models.IntegerField(default=0)),
                ('video5', models.IntegerField(default=0)),
                ('video6', models.IntegerField(default=0)),
                ('video7', models.IntegerField(default=0)),
                ('video8', models.IntegerField(default=0)),
                ('video9', models.IntegerField(default=0)),
                ('video10', models.IntegerField(default=0)),
                ('video11', models.IntegerField(default=0)),
                ('video12', models.IntegerField(default=0)),
                ('video13', models.IntegerField(default=0)),
                ('video14', models.IntegerField(default=0)),
                ('video15', models.IntegerField(default=0)),
                ('video16', models.IntegerField(default=0)),
                ('video17', models.IntegerField(default=0)),
                ('percentage', models.FloatField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videodb', to='main.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
