# Generated by Django 4.1.5 on 2023-02-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_videodb_delete_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodb',
            old_name='video1',
            new_name='video1_1',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video10',
            new_name='video2_1',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video11',
            new_name='video3_1',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video12',
            new_name='video3_10',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video14',
            new_name='video3_11',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video13',
            new_name='video3_2',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video15',
            new_name='video3_3',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video16',
            new_name='video3_4',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video17',
            new_name='video3_5',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3',
            new_name='video3_6',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video2',
            new_name='video3_7',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video4',
            new_name='video3_8',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video5',
            new_name='video3_9',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video6',
            new_name='video4_1',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video7',
            new_name='video4_2',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video8',
            new_name='video5_1',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video9',
            new_name='video5_2',
        ),
        migrations.AlterField(
            model_name='videodb',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
