# Generated by Django 4.1.5 on 2023-02-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_video1_videodb_video1_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodb',
            old_name='video1_1',
            new_name='video1',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video2_1',
            new_name='video10',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_1',
            new_name='video11',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_10',
            new_name='video12',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_11',
            new_name='video13',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_2',
            new_name='video14',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_3',
            new_name='video15',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_4',
            new_name='video16',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_5',
            new_name='video17',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_6',
            new_name='video2',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_7',
            new_name='video3',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_8',
            new_name='video4',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3_9',
            new_name='video5',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video4_1',
            new_name='video6',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video4_2',
            new_name='video7',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video5_1',
            new_name='video8',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video5_2',
            new_name='video9',
        ),
    ]
