# Generated by Django 4.1.6 on 2023-02-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_video1_1_videodb_video1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodb',
            old_name='video1',
            new_name='videoP1',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video10',
            new_name='videoP10',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video11',
            new_name='videoP11',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video12',
            new_name='videoP12',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video13',
            new_name='videoP13',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video14',
            new_name='videoP14',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video15',
            new_name='videoP15',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video16',
            new_name='videoP16',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video17',
            new_name='videoP17',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video2',
            new_name='videoP2',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video3',
            new_name='videoP3',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video4',
            new_name='videoP4',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video5',
            new_name='videoP5',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video6',
            new_name='videoP6',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video7',
            new_name='videoP7',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video8',
            new_name='videoP8',
        ),
        migrations.RenameField(
            model_name='videodb',
            old_name='video9',
            new_name='videoP9',
        ),
    ]
