# Generated by Django 4.1.6 on 2023-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_video1_videodb_videop1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodb',
            name='percentage',
        ),
        migrations.AddField(
            model_name='user',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
